# Generated by Django 4.0.5 on 2022-07-09 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_name', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='module_name',
            table=None,
        ),
    ]
