# Generated by Django 4.0.5 on 2022-07-09 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_name', '0002_alter_module_name_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='module_name',
            table='module_name',
        ),
    ]
