# Generated by Django 4.0.5 on 2022-07-09 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('watch_name', models.CharField(max_length=255)),
                ('watch_price', models.CharField(blank=True, max_length=255)),
                ('watch_detail', models.CharField(blank=True, max_length=2000)),
                ('watch_image', models.FileField(default='default.jpg', upload_to='static/images')),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
