# Generated by Django 4.0.5 on 2022-07-09 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='watch_stock',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
