# Generated by Django 4.0.5 on 2022-07-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_watch_image2_product_watch_image3'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_catog',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='watch_tec',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
