# Generated by Django 4.0.5 on 2022-07-12 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_product_catog_product_watch_tec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='watch_price',
            field=models.FloatField(blank=True),
        ),
    ]
