# Generated by Django 4.0.5 on 2022-06-23 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'signup',
            },
        ),
    ]
