# Generated by Django 4.0.5 on 2022-07-06 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Signup',
        ),
    ]
