# Generated by Django 4.0.5 on 2022-06-21 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_app_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app',
            old_name='itemName',
            new_name='username',
        ),
    ]
