# Generated by Django 4.0.5 on 2022-06-22 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_itemname_app_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='user_image',
            field=models.FileField(default='default', upload_to='static/images/image'),
        ),
    ]
