# Generated by Django 4.0.5 on 2022-06-23 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_app_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='user_image',
            field=models.FileField(default='default.jpg', upload_to='static/images'),
        ),
    ]
