# Generated by Django 4.0.5 on 2022-07-06 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_app_user_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app',
            old_name='password',
            new_name='details',
        ),
        migrations.RenameField(
            model_name='app',
            old_name='username',
            new_name='watch',
        ),
        migrations.AddField(
            model_name='app',
            name='price',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
