# Generated by Django 4.0.5 on 2022-07-18 09:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_password_app_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=200)),
                ('feedback', models.CharField(max_length=250)),
                ('date_posted', models.DateTimeField(default=datetime.datetime(2022, 7, 18, 15, 13, 46, 196231))),
            ],
        ),
    ]
