# Generated by Django 4.0.5 on 2022-07-17 03:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordertable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('order_image', models.FileField(default='default.jpg', upload_to='static/images')),
                ('product_brand', models.CharField(blank=True, max_length=255)),
                ('order_name', models.CharField(max_length=255)),
                ('order_price', models.FloatField(blank=True)),
                ('order_address', models.CharField(blank=True, max_length=2000)),
                ('order_quantity', models.CharField(blank=True, max_length=255)),
                ('order_phonenumber', models.CharField(blank=True, max_length=255)),
                ('order_pincode', models.CharField(blank=True, max_length=255)),
                ('order_email', models.CharField(blank=True, max_length=255)),
                ('order_payment', models.CharField(blank=True, max_length=255)),
                ('order_total', models.CharField(blank=True, max_length=255)),
                ('order_date', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ordertable',
            },
        ),
    ]
